### ISSUE TITLE
ArgumentError: expected an attributes Hash

### ISSUE THREAD

**Issue by yashwinkumar** [hiringthing/hiringthing_api#1]
[4] pry(main)> myjob = HiringThing::Jobs.find(21587)
ArgumentError: expected an attributes Hash, got [{"id"=>21587, "company"=>"Jobhuk", "job_code"=>"", "title"=>"Ruby on Rails", "abstract"=>"Ruby on Rails", "description"=>"<p>Ruby on Rails</p>", "city"=>"Austin", "state"=>"TX", "country"=>"United States", "archived"=>false, "hidden"=>false, "url"=>"http://ht-jobs.net/S4RTCBS", "created_at"=>"2015-04-20T13:36:26.000-05:00", "applicants"=>1, "new_applicants"=>1}]
from /home/ashwin/.rvm/gems/ruby-1.9.3-p545/gems/activeresource-3.2.8/lib/active_resource/base.rb:1255:in `load'

**Comment by joshuasiler** [comment]
This code has been moved and is no longer being maintained here. Please find the latest version [here](https://github.com/applicant-tracking/applicant_tracking_api)

This issue solved in new repo.
